name: explore
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geoflutterfire:
    git: git://github.com/naveenbharadwaj19/GeoFlutterFire.git
  another_flushbar: ^1.10.17
  app_settings: ^4.1.0
  blurhash: ^0.2.1
  cached_network_image: ^2.5.1
  change_app_package_name: ^0.1.2
  circular_check_box: ^1.0.4
  circular_countdown_timer: ^0.1.0
  clippy_flutter: ^1.1.1
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.0
  email_validator: ^2.0.1
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_ml_vision: ^0.11.0
  firebase_performance: ^0.6.0
  firebase_storage: ^8.0.0
  flare_flutter: ^2.0.6
  flutter_blurhash: ^0.5.0
  flutter_holo_date_picker: ^0.3.4+1
  flutter_secure_storage: ^4.1.0
  flutter_snake_navigationbar: ^0.5.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  gender_selection: ^1.0.0
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  google_sign_in: ^5.0.0
  http: ^0.13.0
  image_cropper: ^1.3.1
  image_picker: ^0.7.3
  intl: ^0.17.0
  lottie: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  page_transition: ^1.1.7+2
  pinput: ^1.2.0
  provider: ^5.0.0
  random_string: ^2.1.0
  responsive_framework: ^0.1.0
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_background_img/welcome_bg.jpg
    - assets/app_images/explore_logo.png
    - assets/app_images/explore_black_logo.png
    - assets/app_images/explore_org_logo.png
    - assets/app_images/male.png
    - assets/app_images/female.png
    - assets/app_images/explore_plain_logo.png
    - assets/app_background_img/welcome_bg_2.png
    - assets/app_images/photo_img_bg.png
    - assets/svg/explore_logo.svg
    - assets/svg/google_icon.svg
    - assets/svg/nothing_to_explore_2.svg
    - assets/svg/email_verf_icon.svg
    - assets/animations/successCheck.flr
    - assets/animations/SearchEmail.flr
    - assets/animations/location_pin.flr
    - assets/animations/no_wifi.flr
    - assets/animations/infinity.json
    - assets/animations/heart1_trial.json
    - assets/animations/heart2_trial.json
    - assets/animations/nothing_to_explore.json
    - assets/animations/location_pin.json
    - assets/animations/no_wifi.json
    - assets/animations/heart_final.json
    - assets/animations/star_final.json
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # Fonts
  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/Domine-Regular.ttf
        - asset: assets/fonts/Domine-Bold.ttf
          style: italic

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 700

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

    # Icons
    - family: MaleIcon
      fonts:
        - asset: assets/fonts/MaleIcon.ttf

    - family: FemaleIcon
      fonts:
        - asset: assets/fonts/FemaleIcon.ttf

    - family: OtherGenders
      fonts:
        - asset: assets/fonts/OtherGenders.ttf

    - family: GalleryIcon
      fonts:
        - asset: assets/fonts/GalleryIcon.ttf

    - family: BottomNavigationBarIcons
      fonts:
        - asset: assets/fonts/BottomNavigationBarIcons.ttf

    - family: Filter
      fonts:
        - asset: assets/fonts/Filter.ttf

    - family: HomeIconOrg # alternative for home icon
      fonts:
        - asset: assets/fonts/HomeIconOrg.ttf

    - family: StarRoundedIcon
      fonts:
        - asset: assets/fonts/StarRoundedIcon.ttf

    - family: FilterReport #noun icon
      fonts:
        - asset: assets/fonts/FilterReport.ttf

    - family: ReportFilterIcons
      fonts:
        - asset: assets/fonts/ReportFilterIcons.ttf
        # - asset: assets/fonts/Domine-Bold.ttf
        # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
