/// Flutter icons FemaleIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FemaleIcon
///      fonts:
///       - asset: fonts/FemaleIcon.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class FemaleIcon {
  FemaleIcon._();

  static const _kFontFam = 'FemaleIcon';
  static const _kFontPkg = null;

  static const IconData female = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
