// @dart=2.9
/// Flutter icons FilterReport
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FilterReport
///      fonts:
///       - asset: fonts/FilterReport.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FilterReport {
  FilterReport._();

  static const _kFontFam = 'FilterReport';
  static const String  _kFontPkg = null;

  static const IconData noun_filter_3324737 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_caution_3320810 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
