/// Flutter icons HomeLove
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeLove
///      fonts:
///       - asset: fonts/HomeLove.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeLove {
  HomeLove._();

  static const _kFontFam = 'HomeLove';
  static const String _kFontPkg = null;

  static const IconData noun_home_love_2283770 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
