/// Flutter icons ProfileMyInterestsIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileMyInterestsIcons
///      fonts:
///       - asset: fonts/ProfileMyInterestsIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class ProfileMyInterestsIcons {
  ProfileMyInterestsIcons._();

  static const _kFontFam = 'ProfileMyInterestsIcons';
  static const String? _kFontPkg = null;

  static const IconData picture_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData design = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData makeup = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData making_video = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photography = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData singing = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData art = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData craft = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dancing = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData writing = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData film_tv = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noodles_pastas = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sweet_tooth = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegan = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegetarain = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whiskey = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biryani = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData concerts = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData festivals = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData museums_galleries = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night_club = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cinema = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stand_up = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamster = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lizard = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rabbit = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snake = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birds = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reading = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gymnastics = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handball = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData martial_arts = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rowing = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skateboarding = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_boarding = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surfing = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badmintion = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bouldering = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData athletics = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_ball = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ping_pong = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_games = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooking = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baking = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData board_game = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData take_out = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gardening = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city_breaks = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fishing_trips = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hiking_trips = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road_trips = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spa_weekends = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_packing = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaches = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camping = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creativity = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empathy = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData intelligence = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData positivity = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData self_awarness = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData being_open_minded = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData being_romantic = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confidence = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_awarness = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData being_active = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sense_of_humor = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambition = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData being_family_oriented = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sense_of_adventure = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
