/// Flutter icons ProfileIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileIcons
///      fonts:
///       - asset: fonts/ProfileIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProfileIcons {
  ProfileIcons._();

  static const _kFontFam = 'ProfileIcons';
  static const String? _kFontPkg = null;

  static const IconData smoking = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData height = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education_level = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_interests = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_signs = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kids = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData looking_for = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about_me = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drinking = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exercise = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
