/// Flutter icons StarRoundedIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StarRoundedIcon
///      fonts:
///       - asset: fonts/StarRoundedIcon.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class StarRoundedIcon {
  StarRoundedIcon._();

  static const _kFontFam = 'StarRoundedIcon';
  static const String _kFontPkg = null;

  static const IconData star = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
